language: php
php:
  - 5.5
  - 5.6
  - 7.0 
  - 7.1 
branches:
  only:
    - master
before_install:
  - travis_retry composer self-update
  - composer install
script:
  - composer test
  - composer style
